"""Initial migration.

Revision ID: 1dce299a8445
Revises: 
Create Date: 2024-01-30 10:33:16.226983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1dce299a8445'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_cart_product_id', 'cart', ['product_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_cart_user_id', 'user', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.drop_constraint('fk_cart_product_id', type_='foreignkey')
        batch_op.drop_constraint('fk_cart_user_id', type_='foreignkey')
        batch_op.drop_column('product_id')

    # ### end Alembic commands ###
